### ISSUE TITLE
Fix: 무한스크롤 기능 및 디자인 수정

### ISSUE THREAD

**Issue by biiit4894** [biiit4894/hodu-fe-project#8]
## 📌  Feature Issue

- 유저 편의성과 디자인적 통일성을 고려해 무한스크롤 기능을 수정합니다.
- 무한스크롤 기능의 문제는 다음과 같습니다.
    1. 스크롤을 올려도 이미지가 로딩됨 
    2. 이미지 로딩에 제한이 없어 사이트 최하단의 footer를 조회하기 위해 강제로 스크롤을 내려야 함
    3. 이미지 로딩 시 그리드 규격이 일정하지 않음

## 💨 Related Pull Requests
- #9 
- #11 
- #12

## 📝  To-do

- 기능상 수정사항
    - [x] 스크롤을 내릴 때에만 이미지가 로딩되도록 수정
    - [x] 이미지 로딩이 종료될 수 있도록 fetch에 제한 설정
    - [x] 새로고침 버튼 추가
- 디자인상 수정사항
    - [x] 이미지 로딩 시 그리드 규격을 맞추도록 수정
    - [x] 이미지 로딩이 시작하면 푸터가 고정되도록 수정
    - [x] 이미지 fetch 완료 전 로딩 이미지 출력
